<?php 
return array (
  'site_name' => '广州市爱养车汽车服务公司',
  'site_title' => '广州市爱养车汽车服务公司',
  'site_logo' => 'http://www.nsacg.com/uploads/j/jifbjv1429543374/8/c/4/3/thumb_554479ca58740.png',
  'site_url' => 'http://www.nsacg.com',
  'site_twm' => '',
  'site_my' => '南沙爱车港助手',
  'server_key' => '123',
  'liaotian_key' => '123',
  'appid' => '',
  'secret' => '',
  'server_topdomain' => '123',
  'connectout' => '用户已到期，请联系管理员或客服充值',
  'ischeckuser' => 'true',
  'reg_needmp' => 'false',
  'open_biz' => '1',
  'isclosekuser' => 'true',
  'demo' => 'true',
  'reg_groupid' => '2',
  'reg_validdays' => '30',
  'router_key' => '',
  'ipc' => '粤ICP备15038267号-1',
  'site_qq' => '273169987',
  'site_mp' => '13928846100',
  'baidu_map_api' => '2b79c282b0f365ca9782cceb499e6022',
  'site_email' => '273169987@qq.com',
  'keyword' => '微信公众账号,微信公众平台,微信公众账号开发,微信二次开发,微信接口开发,微信托管服务,微信营销,微信公众平台接口开发',
  'content' => '微信公众平台接口开发、托管、营销活动、二次开发',
  'countsz' => '',
  'copyright' => 'Copyright (c) 2015 版权所有',
  'close_help' => '0',
);